import { gql, request } from 'graphql-request';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import useSWR from 'swr';
import styles from '../styles/Home.module.css';

const uri = 'https://tatsu513.com/graphql';

const query = gql`
  query {
    posts {
      nodes {
        id
        title
        content
      }
    }
  }
`;

const Home: NextPage = () => {
  const { data, error } = useSWR<any>(
    query,
    (
      query, //👈ポイント
    ) => request(uri, query),
  );

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  console.log({ data });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default Home;
