import { gql, request } from 'graphql-request';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import useSWR from 'swr';
import styles from '../styles/Home.module.css';
import useGetPosts from 'hooks/useGetPosts';

const uri = 'https://tatsu513.com/graphql';

const Home: NextPage = () => {
  const a = process.env.NEXT_PUBLIC_WP_API_URL;
  const { data, error } = useGetPosts();
  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ul>
        {data.map((post) => (
          <li key={post.id}>{post.title}</li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
